services:
  web:
    build:
      context: ./
      dockerfile: development.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  db:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 5s
      retries: 30
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
  bundle: